num1=float(input("Enter value number1 : "))
num2=float(input("Enter value number2 : "))
num3=float(input("Enter value number3 : "))

MinValue=min (num1,num2,num3)
MaxValue=max(num1,num2,num3)
print()
print("You enter number :",num1,num2,num3)
print("Maximum value :",MaxValue)
print("Minimum value :",MinValue)
